version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nutrivision-backend
    restart: always
    volumes:
      - nutrivision_data:/app
    environment:
      - DATABASE_URL=sqlite:///./nutrivision.db
      - VIRTUAL_HOST=api.nutrivision.live
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.nutrivision.live
    env_file:
      - ./backend/.env

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: nutrivision-frontend
    restart: always
    environment:
      - VIRTUAL_HOST=nutrivision.live
      - LETSENCRYPT_HOST=nutrivision.live
    depends_on:
      - backend

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nutrivision_data:
  conf:
  vhost:
  html: (
  certs:
  acme:
